### ISSUE TITLE
Platybrowser doesn't work with aws credentials file

### ISSUE THREAD

**Issue by constantinpape** [platybrowser/mobie-viewer-fiji#92]
Fails with:
```
[ERROR] Module threw exception
com.amazonaws.services.s3.model.AmazonS3Exception: The access key ID you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: 1612591D9493B3BE; S3 Extended Request ID: 50f73ea1-7aa8-4b55-8b58-9776bac7048a), S3 Extended Request ID: 50f73ea1-7aa8-4b55-8b58-9776bac7048a
```
and works if the credentials file is removed.

**Comment by tischi** [comment]
1. Could you ask Josep? Because this is an error that is different from the ones I have seen/
2. Could you (e.g. via Slack) send me your credentials file for debugging?

**Comment by constantinpape** [comment]
>     1. Could you ask Josep? Because this is an error that is different from the ones I have seen/

Ok, I can ask him at some point. Just for references, these credentials are for an actual aws s3 account.

Will send it to you later.

**Comment by constantinpape** [comment]
Ok, I actually made a duplicate of my own issue :D.
I am closing this one in favor of the newer one #94, because it is more specific.
